# Generated by Django 4.0.5 on 2022-07-01 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_gestion', '0002_alter_persona_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
